package com.example.neo.mybatis.mapper;

import com.example.neo.mybatis.model.NeoCompany;
import com.example.neo.mybatis.model.NeoCompanyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NeoCompanyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_company
     *
     * @mbg.generated
     */
    long countByExample(NeoCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_company
     *
     * @mbg.generated
     */
    int deleteByExample(NeoCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_company
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_company
     *
     * @mbg.generated
     */
    int insert(NeoCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_company
     *
     * @mbg.generated
     */
    int insertSelective(NeoCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_company
     *
     * @mbg.generated
     */
    List<NeoCompany> selectByExample(NeoCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_company
     *
     * @mbg.generated
     */
    NeoCompany selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_company
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") NeoCompany record, @Param("example") NeoCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_company
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") NeoCompany record, @Param("example") NeoCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_company
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(NeoCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_company
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(NeoCompany record);
}