package com.example.neo.mybatis.mapper;

import com.example.neo.mybatis.model.NeoCompanyTax;
import com.example.neo.mybatis.model.NeoCompanyTaxExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NeoCompanyTaxMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_company_tax
     *
     * @mbg.generated
     */
    long countByExample(NeoCompanyTaxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_company_tax
     *
     * @mbg.generated
     */
    int deleteByExample(NeoCompanyTaxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_company_tax
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_company_tax
     *
     * @mbg.generated
     */
    int insert(NeoCompanyTax record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_company_tax
     *
     * @mbg.generated
     */
    int insertSelective(NeoCompanyTax record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_company_tax
     *
     * @mbg.generated
     */
    List<NeoCompanyTax> selectByExample(NeoCompanyTaxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_company_tax
     *
     * @mbg.generated
     */
    NeoCompanyTax selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_company_tax
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") NeoCompanyTax record, @Param("example") NeoCompanyTaxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_company_tax
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") NeoCompanyTax record, @Param("example") NeoCompanyTaxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_company_tax
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(NeoCompanyTax record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_company_tax
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(NeoCompanyTax record);
}