package com.example.neo.mybatis.mapper;

import com.example.neo.mybatis.model.NeoInvoice;
import com.example.neo.mybatis.model.NeoInvoiceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NeoInvoiceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_invoice
     *
     * @mbg.generated
     */
    long countByExample(NeoInvoiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_invoice
     *
     * @mbg.generated
     */
    int deleteByExample(NeoInvoiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_invoice
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_invoice
     *
     * @mbg.generated
     */
    int insert(NeoInvoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_invoice
     *
     * @mbg.generated
     */
    int insertSelective(NeoInvoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_invoice
     *
     * @mbg.generated
     */
    List<NeoInvoice> selectByExample(NeoInvoiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_invoice
     *
     * @mbg.generated
     */
    NeoInvoice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_invoice
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") NeoInvoice record, @Param("example") NeoInvoiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_invoice
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") NeoInvoice record, @Param("example") NeoInvoiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_invoice
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(NeoInvoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_invoice
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(NeoInvoice record);
}