package com.example.neo.mybatis.mapper;

import com.example.neo.mybatis.model.NeoRole;
import com.example.neo.mybatis.model.NeoRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NeoRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_role
     *
     * @mbg.generated
     */
    long countByExample(NeoRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_role
     *
     * @mbg.generated
     */
    int deleteByExample(NeoRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_role
     *
     * @mbg.generated
     */
    int insert(NeoRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_role
     *
     * @mbg.generated
     */
    int insertSelective(NeoRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_role
     *
     * @mbg.generated
     */
    List<NeoRole> selectByExample(NeoRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_role
     *
     * @mbg.generated
     */
    NeoRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_role
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") NeoRole record, @Param("example") NeoRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_role
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") NeoRole record, @Param("example") NeoRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(NeoRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(NeoRole record);
}