package com.example.neo.mybatis.mapper;

import com.example.neo.mybatis.model.NeoRechargeRecord;
import com.example.neo.mybatis.model.NeoRechargeRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NeoRechargeRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_recharge_record
     *
     * @mbg.generated
     */
    long countByExample(NeoRechargeRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_recharge_record
     *
     * @mbg.generated
     */
    int deleteByExample(NeoRechargeRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_recharge_record
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_recharge_record
     *
     * @mbg.generated
     */
    int insert(NeoRechargeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_recharge_record
     *
     * @mbg.generated
     */
    int insertSelective(NeoRechargeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_recharge_record
     *
     * @mbg.generated
     */
    List<NeoRechargeRecord> selectByExample(NeoRechargeRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_recharge_record
     *
     * @mbg.generated
     */
    NeoRechargeRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_recharge_record
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") NeoRechargeRecord record, @Param("example") NeoRechargeRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_recharge_record
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") NeoRechargeRecord record, @Param("example") NeoRechargeRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_recharge_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(NeoRechargeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_recharge_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(NeoRechargeRecord record);
}