package com.example.neo.mybatis.mapper;

import com.example.neo.mybatis.model.NeoUser;
import com.example.neo.mybatis.model.NeoUserExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface NeoUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_user
     *
     * @mbg.generated
     */
    long countByExample(NeoUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_user
     *
     * @mbg.generated
     */
    int deleteByExample(NeoUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_user
     *
     * @mbg.generated
     */
    int insert(NeoUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_user
     *
     * @mbg.generated
     */
    int insertSelective(NeoUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_user
     *
     * @mbg.generated
     */
    List<NeoUser> selectByExample(NeoUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_user
     *
     * @mbg.generated
     */
    NeoUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") NeoUser record, @Param("example") NeoUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") NeoUser record, @Param("example") NeoUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(NeoUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(NeoUser record);
}
