package com.example.neo.mybatis.mapper;

import com.example.neo.mybatis.model.NoCompany;
import com.example.neo.mybatis.model.NoCompanyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NoCompanyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_company
     *
     * @mbg.generated
     */
    long countByExample(NoCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_company
     *
     * @mbg.generated
     */
    int deleteByExample(NoCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_company
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_company
     *
     * @mbg.generated
     */
    int insert(NoCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_company
     *
     * @mbg.generated
     */
    int insertSelective(NoCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_company
     *
     * @mbg.generated
     */
    List<NoCompany> selectByExample(NoCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_company
     *
     * @mbg.generated
     */
    NoCompany selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_company
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") NoCompany record, @Param("example") NoCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_company
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") NoCompany record, @Param("example") NoCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_company
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(NoCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_company
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(NoCompany record);
}