package com.example.neo.mybatis.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class neoCompanyExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table neo_company
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table neo_company
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table neo_company
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_company
     *
     * @mbg.generated
     */
    public neoCompanyExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_company
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_company
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_company
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_company
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_company
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_company
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_company
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_company
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_company
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_company
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table neo_company
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCompanyNameIsNull() {
            addCriterion("company_name is null");
            return (Criteria) this;
        }

        public Criteria andCompanyNameIsNotNull() {
            addCriterion("company_name is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyNameEqualTo(String value) {
            addCriterion("company_name =", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotEqualTo(String value) {
            addCriterion("company_name <>", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameGreaterThan(String value) {
            addCriterion("company_name >", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameGreaterThanOrEqualTo(String value) {
            addCriterion("company_name >=", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameLessThan(String value) {
            addCriterion("company_name <", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameLessThanOrEqualTo(String value) {
            addCriterion("company_name <=", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameLike(String value) {
            addCriterion("company_name like", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotLike(String value) {
            addCriterion("company_name not like", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameIn(List<String> values) {
            addCriterion("company_name in", values, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotIn(List<String> values) {
            addCriterion("company_name not in", values, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameBetween(String value1, String value2) {
            addCriterion("company_name between", value1, value2, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotBetween(String value1, String value2) {
            addCriterion("company_name not between", value1, value2, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyTaxIsNull() {
            addCriterion("company_tax is null");
            return (Criteria) this;
        }

        public Criteria andCompanyTaxIsNotNull() {
            addCriterion("company_tax is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyTaxEqualTo(String value) {
            addCriterion("company_tax =", value, "companyTax");
            return (Criteria) this;
        }

        public Criteria andCompanyTaxNotEqualTo(String value) {
            addCriterion("company_tax <>", value, "companyTax");
            return (Criteria) this;
        }

        public Criteria andCompanyTaxGreaterThan(String value) {
            addCriterion("company_tax >", value, "companyTax");
            return (Criteria) this;
        }

        public Criteria andCompanyTaxGreaterThanOrEqualTo(String value) {
            addCriterion("company_tax >=", value, "companyTax");
            return (Criteria) this;
        }

        public Criteria andCompanyTaxLessThan(String value) {
            addCriterion("company_tax <", value, "companyTax");
            return (Criteria) this;
        }

        public Criteria andCompanyTaxLessThanOrEqualTo(String value) {
            addCriterion("company_tax <=", value, "companyTax");
            return (Criteria) this;
        }

        public Criteria andCompanyTaxLike(String value) {
            addCriterion("company_tax like", value, "companyTax");
            return (Criteria) this;
        }

        public Criteria andCompanyTaxNotLike(String value) {
            addCriterion("company_tax not like", value, "companyTax");
            return (Criteria) this;
        }

        public Criteria andCompanyTaxIn(List<String> values) {
            addCriterion("company_tax in", values, "companyTax");
            return (Criteria) this;
        }

        public Criteria andCompanyTaxNotIn(List<String> values) {
            addCriterion("company_tax not in", values, "companyTax");
            return (Criteria) this;
        }

        public Criteria andCompanyTaxBetween(String value1, String value2) {
            addCriterion("company_tax between", value1, value2, "companyTax");
            return (Criteria) this;
        }

        public Criteria andCompanyTaxNotBetween(String value1, String value2) {
            addCriterion("company_tax not between", value1, value2, "companyTax");
            return (Criteria) this;
        }

        public Criteria andCompanyLocationIsNull() {
            addCriterion("company_location is null");
            return (Criteria) this;
        }

        public Criteria andCompanyLocationIsNotNull() {
            addCriterion("company_location is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyLocationEqualTo(String value) {
            addCriterion("company_location =", value, "companyLocation");
            return (Criteria) this;
        }

        public Criteria andCompanyLocationNotEqualTo(String value) {
            addCriterion("company_location <>", value, "companyLocation");
            return (Criteria) this;
        }

        public Criteria andCompanyLocationGreaterThan(String value) {
            addCriterion("company_location >", value, "companyLocation");
            return (Criteria) this;
        }

        public Criteria andCompanyLocationGreaterThanOrEqualTo(String value) {
            addCriterion("company_location >=", value, "companyLocation");
            return (Criteria) this;
        }

        public Criteria andCompanyLocationLessThan(String value) {
            addCriterion("company_location <", value, "companyLocation");
            return (Criteria) this;
        }

        public Criteria andCompanyLocationLessThanOrEqualTo(String value) {
            addCriterion("company_location <=", value, "companyLocation");
            return (Criteria) this;
        }

        public Criteria andCompanyLocationLike(String value) {
            addCriterion("company_location like", value, "companyLocation");
            return (Criteria) this;
        }

        public Criteria andCompanyLocationNotLike(String value) {
            addCriterion("company_location not like", value, "companyLocation");
            return (Criteria) this;
        }

        public Criteria andCompanyLocationIn(List<String> values) {
            addCriterion("company_location in", values, "companyLocation");
            return (Criteria) this;
        }

        public Criteria andCompanyLocationNotIn(List<String> values) {
            addCriterion("company_location not in", values, "companyLocation");
            return (Criteria) this;
        }

        public Criteria andCompanyLocationBetween(String value1, String value2) {
            addCriterion("company_location between", value1, value2, "companyLocation");
            return (Criteria) this;
        }

        public Criteria andCompanyLocationNotBetween(String value1, String value2) {
            addCriterion("company_location not between", value1, value2, "companyLocation");
            return (Criteria) this;
        }

        public Criteria andCompanyBankNameIsNull() {
            addCriterion("company_bank_name is null");
            return (Criteria) this;
        }

        public Criteria andCompanyBankNameIsNotNull() {
            addCriterion("company_bank_name is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyBankNameEqualTo(String value) {
            addCriterion("company_bank_name =", value, "companyBankName");
            return (Criteria) this;
        }

        public Criteria andCompanyBankNameNotEqualTo(String value) {
            addCriterion("company_bank_name <>", value, "companyBankName");
            return (Criteria) this;
        }

        public Criteria andCompanyBankNameGreaterThan(String value) {
            addCriterion("company_bank_name >", value, "companyBankName");
            return (Criteria) this;
        }

        public Criteria andCompanyBankNameGreaterThanOrEqualTo(String value) {
            addCriterion("company_bank_name >=", value, "companyBankName");
            return (Criteria) this;
        }

        public Criteria andCompanyBankNameLessThan(String value) {
            addCriterion("company_bank_name <", value, "companyBankName");
            return (Criteria) this;
        }

        public Criteria andCompanyBankNameLessThanOrEqualTo(String value) {
            addCriterion("company_bank_name <=", value, "companyBankName");
            return (Criteria) this;
        }

        public Criteria andCompanyBankNameLike(String value) {
            addCriterion("company_bank_name like", value, "companyBankName");
            return (Criteria) this;
        }

        public Criteria andCompanyBankNameNotLike(String value) {
            addCriterion("company_bank_name not like", value, "companyBankName");
            return (Criteria) this;
        }

        public Criteria andCompanyBankNameIn(List<String> values) {
            addCriterion("company_bank_name in", values, "companyBankName");
            return (Criteria) this;
        }

        public Criteria andCompanyBankNameNotIn(List<String> values) {
            addCriterion("company_bank_name not in", values, "companyBankName");
            return (Criteria) this;
        }

        public Criteria andCompanyBankNameBetween(String value1, String value2) {
            addCriterion("company_bank_name between", value1, value2, "companyBankName");
            return (Criteria) this;
        }

        public Criteria andCompanyBankNameNotBetween(String value1, String value2) {
            addCriterion("company_bank_name not between", value1, value2, "companyBankName");
            return (Criteria) this;
        }

        public Criteria andCompanyBankNumberIsNull() {
            addCriterion("company_bank_number is null");
            return (Criteria) this;
        }

        public Criteria andCompanyBankNumberIsNotNull() {
            addCriterion("company_bank_number is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyBankNumberEqualTo(String value) {
            addCriterion("company_bank_number =", value, "companyBankNumber");
            return (Criteria) this;
        }

        public Criteria andCompanyBankNumberNotEqualTo(String value) {
            addCriterion("company_bank_number <>", value, "companyBankNumber");
            return (Criteria) this;
        }

        public Criteria andCompanyBankNumberGreaterThan(String value) {
            addCriterion("company_bank_number >", value, "companyBankNumber");
            return (Criteria) this;
        }

        public Criteria andCompanyBankNumberGreaterThanOrEqualTo(String value) {
            addCriterion("company_bank_number >=", value, "companyBankNumber");
            return (Criteria) this;
        }

        public Criteria andCompanyBankNumberLessThan(String value) {
            addCriterion("company_bank_number <", value, "companyBankNumber");
            return (Criteria) this;
        }

        public Criteria andCompanyBankNumberLessThanOrEqualTo(String value) {
            addCriterion("company_bank_number <=", value, "companyBankNumber");
            return (Criteria) this;
        }

        public Criteria andCompanyBankNumberLike(String value) {
            addCriterion("company_bank_number like", value, "companyBankNumber");
            return (Criteria) this;
        }

        public Criteria andCompanyBankNumberNotLike(String value) {
            addCriterion("company_bank_number not like", value, "companyBankNumber");
            return (Criteria) this;
        }

        public Criteria andCompanyBankNumberIn(List<String> values) {
            addCriterion("company_bank_number in", values, "companyBankNumber");
            return (Criteria) this;
        }

        public Criteria andCompanyBankNumberNotIn(List<String> values) {
            addCriterion("company_bank_number not in", values, "companyBankNumber");
            return (Criteria) this;
        }

        public Criteria andCompanyBankNumberBetween(String value1, String value2) {
            addCriterion("company_bank_number between", value1, value2, "companyBankNumber");
            return (Criteria) this;
        }

        public Criteria andCompanyBankNumberNotBetween(String value1, String value2) {
            addCriterion("company_bank_number not between", value1, value2, "companyBankNumber");
            return (Criteria) this;
        }

        public Criteria andCompanyIndustryIsNull() {
            addCriterion("company_industry is null");
            return (Criteria) this;
        }

        public Criteria andCompanyIndustryIsNotNull() {
            addCriterion("company_industry is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyIndustryEqualTo(String value) {
            addCriterion("company_industry =", value, "companyIndustry");
            return (Criteria) this;
        }

        public Criteria andCompanyIndustryNotEqualTo(String value) {
            addCriterion("company_industry <>", value, "companyIndustry");
            return (Criteria) this;
        }

        public Criteria andCompanyIndustryGreaterThan(String value) {
            addCriterion("company_industry >", value, "companyIndustry");
            return (Criteria) this;
        }

        public Criteria andCompanyIndustryGreaterThanOrEqualTo(String value) {
            addCriterion("company_industry >=", value, "companyIndustry");
            return (Criteria) this;
        }

        public Criteria andCompanyIndustryLessThan(String value) {
            addCriterion("company_industry <", value, "companyIndustry");
            return (Criteria) this;
        }

        public Criteria andCompanyIndustryLessThanOrEqualTo(String value) {
            addCriterion("company_industry <=", value, "companyIndustry");
            return (Criteria) this;
        }

        public Criteria andCompanyIndustryLike(String value) {
            addCriterion("company_industry like", value, "companyIndustry");
            return (Criteria) this;
        }

        public Criteria andCompanyIndustryNotLike(String value) {
            addCriterion("company_industry not like", value, "companyIndustry");
            return (Criteria) this;
        }

        public Criteria andCompanyIndustryIn(List<String> values) {
            addCriterion("company_industry in", values, "companyIndustry");
            return (Criteria) this;
        }

        public Criteria andCompanyIndustryNotIn(List<String> values) {
            addCriterion("company_industry not in", values, "companyIndustry");
            return (Criteria) this;
        }

        public Criteria andCompanyIndustryBetween(String value1, String value2) {
            addCriterion("company_industry between", value1, value2, "companyIndustry");
            return (Criteria) this;
        }

        public Criteria andCompanyIndustryNotBetween(String value1, String value2) {
            addCriterion("company_industry not between", value1, value2, "companyIndustry");
            return (Criteria) this;
        }

        public Criteria andCompanyRateIsNull() {
            addCriterion("company_rate is null");
            return (Criteria) this;
        }

        public Criteria andCompanyRateIsNotNull() {
            addCriterion("company_rate is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyRateEqualTo(String value) {
            addCriterion("company_rate =", value, "companyRate");
            return (Criteria) this;
        }

        public Criteria andCompanyRateNotEqualTo(String value) {
            addCriterion("company_rate <>", value, "companyRate");
            return (Criteria) this;
        }

        public Criteria andCompanyRateGreaterThan(String value) {
            addCriterion("company_rate >", value, "companyRate");
            return (Criteria) this;
        }

        public Criteria andCompanyRateGreaterThanOrEqualTo(String value) {
            addCriterion("company_rate >=", value, "companyRate");
            return (Criteria) this;
        }

        public Criteria andCompanyRateLessThan(String value) {
            addCriterion("company_rate <", value, "companyRate");
            return (Criteria) this;
        }

        public Criteria andCompanyRateLessThanOrEqualTo(String value) {
            addCriterion("company_rate <=", value, "companyRate");
            return (Criteria) this;
        }

        public Criteria andCompanyRateLike(String value) {
            addCriterion("company_rate like", value, "companyRate");
            return (Criteria) this;
        }

        public Criteria andCompanyRateNotLike(String value) {
            addCriterion("company_rate not like", value, "companyRate");
            return (Criteria) this;
        }

        public Criteria andCompanyRateIn(List<String> values) {
            addCriterion("company_rate in", values, "companyRate");
            return (Criteria) this;
        }

        public Criteria andCompanyRateNotIn(List<String> values) {
            addCriterion("company_rate not in", values, "companyRate");
            return (Criteria) this;
        }

        public Criteria andCompanyRateBetween(String value1, String value2) {
            addCriterion("company_rate between", value1, value2, "companyRate");
            return (Criteria) this;
        }

        public Criteria andCompanyRateNotBetween(String value1, String value2) {
            addCriterion("company_rate not between", value1, value2, "companyRate");
            return (Criteria) this;
        }

        public Criteria andContactNameIsNull() {
            addCriterion("contact_name is null");
            return (Criteria) this;
        }

        public Criteria andContactNameIsNotNull() {
            addCriterion("contact_name is not null");
            return (Criteria) this;
        }

        public Criteria andContactNameEqualTo(String value) {
            addCriterion("contact_name =", value, "contactName");
            return (Criteria) this;
        }

        public Criteria andContactNameNotEqualTo(String value) {
            addCriterion("contact_name <>", value, "contactName");
            return (Criteria) this;
        }

        public Criteria andContactNameGreaterThan(String value) {
            addCriterion("contact_name >", value, "contactName");
            return (Criteria) this;
        }

        public Criteria andContactNameGreaterThanOrEqualTo(String value) {
            addCriterion("contact_name >=", value, "contactName");
            return (Criteria) this;
        }

        public Criteria andContactNameLessThan(String value) {
            addCriterion("contact_name <", value, "contactName");
            return (Criteria) this;
        }

        public Criteria andContactNameLessThanOrEqualTo(String value) {
            addCriterion("contact_name <=", value, "contactName");
            return (Criteria) this;
        }

        public Criteria andContactNameLike(String value) {
            addCriterion("contact_name like", value, "contactName");
            return (Criteria) this;
        }

        public Criteria andContactNameNotLike(String value) {
            addCriterion("contact_name not like", value, "contactName");
            return (Criteria) this;
        }

        public Criteria andContactNameIn(List<String> values) {
            addCriterion("contact_name in", values, "contactName");
            return (Criteria) this;
        }

        public Criteria andContactNameNotIn(List<String> values) {
            addCriterion("contact_name not in", values, "contactName");
            return (Criteria) this;
        }

        public Criteria andContactNameBetween(String value1, String value2) {
            addCriterion("contact_name between", value1, value2, "contactName");
            return (Criteria) this;
        }

        public Criteria andContactNameNotBetween(String value1, String value2) {
            addCriterion("contact_name not between", value1, value2, "contactName");
            return (Criteria) this;
        }

        public Criteria andCompanyFixedTelIsNull() {
            addCriterion("company_fixed_tel is null");
            return (Criteria) this;
        }

        public Criteria andCompanyFixedTelIsNotNull() {
            addCriterion("company_fixed_tel is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyFixedTelEqualTo(String value) {
            addCriterion("company_fixed_tel =", value, "companyFixedTel");
            return (Criteria) this;
        }

        public Criteria andCompanyFixedTelNotEqualTo(String value) {
            addCriterion("company_fixed_tel <>", value, "companyFixedTel");
            return (Criteria) this;
        }

        public Criteria andCompanyFixedTelGreaterThan(String value) {
            addCriterion("company_fixed_tel >", value, "companyFixedTel");
            return (Criteria) this;
        }

        public Criteria andCompanyFixedTelGreaterThanOrEqualTo(String value) {
            addCriterion("company_fixed_tel >=", value, "companyFixedTel");
            return (Criteria) this;
        }

        public Criteria andCompanyFixedTelLessThan(String value) {
            addCriterion("company_fixed_tel <", value, "companyFixedTel");
            return (Criteria) this;
        }

        public Criteria andCompanyFixedTelLessThanOrEqualTo(String value) {
            addCriterion("company_fixed_tel <=", value, "companyFixedTel");
            return (Criteria) this;
        }

        public Criteria andCompanyFixedTelLike(String value) {
            addCriterion("company_fixed_tel like", value, "companyFixedTel");
            return (Criteria) this;
        }

        public Criteria andCompanyFixedTelNotLike(String value) {
            addCriterion("company_fixed_tel not like", value, "companyFixedTel");
            return (Criteria) this;
        }

        public Criteria andCompanyFixedTelIn(List<String> values) {
            addCriterion("company_fixed_tel in", values, "companyFixedTel");
            return (Criteria) this;
        }

        public Criteria andCompanyFixedTelNotIn(List<String> values) {
            addCriterion("company_fixed_tel not in", values, "companyFixedTel");
            return (Criteria) this;
        }

        public Criteria andCompanyFixedTelBetween(String value1, String value2) {
            addCriterion("company_fixed_tel between", value1, value2, "companyFixedTel");
            return (Criteria) this;
        }

        public Criteria andCompanyFixedTelNotBetween(String value1, String value2) {
            addCriterion("company_fixed_tel not between", value1, value2, "companyFixedTel");
            return (Criteria) this;
        }

        public Criteria andContactTelIsNull() {
            addCriterion("contact_tel is null");
            return (Criteria) this;
        }

        public Criteria andContactTelIsNotNull() {
            addCriterion("contact_tel is not null");
            return (Criteria) this;
        }

        public Criteria andContactTelEqualTo(String value) {
            addCriterion("contact_tel =", value, "contactTel");
            return (Criteria) this;
        }

        public Criteria andContactTelNotEqualTo(String value) {
            addCriterion("contact_tel <>", value, "contactTel");
            return (Criteria) this;
        }

        public Criteria andContactTelGreaterThan(String value) {
            addCriterion("contact_tel >", value, "contactTel");
            return (Criteria) this;
        }

        public Criteria andContactTelGreaterThanOrEqualTo(String value) {
            addCriterion("contact_tel >=", value, "contactTel");
            return (Criteria) this;
        }

        public Criteria andContactTelLessThan(String value) {
            addCriterion("contact_tel <", value, "contactTel");
            return (Criteria) this;
        }

        public Criteria andContactTelLessThanOrEqualTo(String value) {
            addCriterion("contact_tel <=", value, "contactTel");
            return (Criteria) this;
        }

        public Criteria andContactTelLike(String value) {
            addCriterion("contact_tel like", value, "contactTel");
            return (Criteria) this;
        }

        public Criteria andContactTelNotLike(String value) {
            addCriterion("contact_tel not like", value, "contactTel");
            return (Criteria) this;
        }

        public Criteria andContactTelIn(List<String> values) {
            addCriterion("contact_tel in", values, "contactTel");
            return (Criteria) this;
        }

        public Criteria andContactTelNotIn(List<String> values) {
            addCriterion("contact_tel not in", values, "contactTel");
            return (Criteria) this;
        }

        public Criteria andContactTelBetween(String value1, String value2) {
            addCriterion("contact_tel between", value1, value2, "contactTel");
            return (Criteria) this;
        }

        public Criteria andContactTelNotBetween(String value1, String value2) {
            addCriterion("contact_tel not between", value1, value2, "contactTel");
            return (Criteria) this;
        }

        public Criteria andRecipientNameIsNull() {
            addCriterion("recipient_name is null");
            return (Criteria) this;
        }

        public Criteria andRecipientNameIsNotNull() {
            addCriterion("recipient_name is not null");
            return (Criteria) this;
        }

        public Criteria andRecipientNameEqualTo(String value) {
            addCriterion("recipient_name =", value, "recipientName");
            return (Criteria) this;
        }

        public Criteria andRecipientNameNotEqualTo(String value) {
            addCriterion("recipient_name <>", value, "recipientName");
            return (Criteria) this;
        }

        public Criteria andRecipientNameGreaterThan(String value) {
            addCriterion("recipient_name >", value, "recipientName");
            return (Criteria) this;
        }

        public Criteria andRecipientNameGreaterThanOrEqualTo(String value) {
            addCriterion("recipient_name >=", value, "recipientName");
            return (Criteria) this;
        }

        public Criteria andRecipientNameLessThan(String value) {
            addCriterion("recipient_name <", value, "recipientName");
            return (Criteria) this;
        }

        public Criteria andRecipientNameLessThanOrEqualTo(String value) {
            addCriterion("recipient_name <=", value, "recipientName");
            return (Criteria) this;
        }

        public Criteria andRecipientNameLike(String value) {
            addCriterion("recipient_name like", value, "recipientName");
            return (Criteria) this;
        }

        public Criteria andRecipientNameNotLike(String value) {
            addCriterion("recipient_name not like", value, "recipientName");
            return (Criteria) this;
        }

        public Criteria andRecipientNameIn(List<String> values) {
            addCriterion("recipient_name in", values, "recipientName");
            return (Criteria) this;
        }

        public Criteria andRecipientNameNotIn(List<String> values) {
            addCriterion("recipient_name not in", values, "recipientName");
            return (Criteria) this;
        }

        public Criteria andRecipientNameBetween(String value1, String value2) {
            addCriterion("recipient_name between", value1, value2, "recipientName");
            return (Criteria) this;
        }

        public Criteria andRecipientNameNotBetween(String value1, String value2) {
            addCriterion("recipient_name not between", value1, value2, "recipientName");
            return (Criteria) this;
        }

        public Criteria andRecipientTelIsNull() {
            addCriterion("recipient_tel is null");
            return (Criteria) this;
        }

        public Criteria andRecipientTelIsNotNull() {
            addCriterion("recipient_tel is not null");
            return (Criteria) this;
        }

        public Criteria andRecipientTelEqualTo(String value) {
            addCriterion("recipient_tel =", value, "recipientTel");
            return (Criteria) this;
        }

        public Criteria andRecipientTelNotEqualTo(String value) {
            addCriterion("recipient_tel <>", value, "recipientTel");
            return (Criteria) this;
        }

        public Criteria andRecipientTelGreaterThan(String value) {
            addCriterion("recipient_tel >", value, "recipientTel");
            return (Criteria) this;
        }

        public Criteria andRecipientTelGreaterThanOrEqualTo(String value) {
            addCriterion("recipient_tel >=", value, "recipientTel");
            return (Criteria) this;
        }

        public Criteria andRecipientTelLessThan(String value) {
            addCriterion("recipient_tel <", value, "recipientTel");
            return (Criteria) this;
        }

        public Criteria andRecipientTelLessThanOrEqualTo(String value) {
            addCriterion("recipient_tel <=", value, "recipientTel");
            return (Criteria) this;
        }

        public Criteria andRecipientTelLike(String value) {
            addCriterion("recipient_tel like", value, "recipientTel");
            return (Criteria) this;
        }

        public Criteria andRecipientTelNotLike(String value) {
            addCriterion("recipient_tel not like", value, "recipientTel");
            return (Criteria) this;
        }

        public Criteria andRecipientTelIn(List<String> values) {
            addCriterion("recipient_tel in", values, "recipientTel");
            return (Criteria) this;
        }

        public Criteria andRecipientTelNotIn(List<String> values) {
            addCriterion("recipient_tel not in", values, "recipientTel");
            return (Criteria) this;
        }

        public Criteria andRecipientTelBetween(String value1, String value2) {
            addCriterion("recipient_tel between", value1, value2, "recipientTel");
            return (Criteria) this;
        }

        public Criteria andRecipientTelNotBetween(String value1, String value2) {
            addCriterion("recipient_tel not between", value1, value2, "recipientTel");
            return (Criteria) this;
        }

        public Criteria andRecipientAddressIsNull() {
            addCriterion("recipient_address is null");
            return (Criteria) this;
        }

        public Criteria andRecipientAddressIsNotNull() {
            addCriterion("recipient_address is not null");
            return (Criteria) this;
        }

        public Criteria andRecipientAddressEqualTo(String value) {
            addCriterion("recipient_address =", value, "recipientAddress");
            return (Criteria) this;
        }

        public Criteria andRecipientAddressNotEqualTo(String value) {
            addCriterion("recipient_address <>", value, "recipientAddress");
            return (Criteria) this;
        }

        public Criteria andRecipientAddressGreaterThan(String value) {
            addCriterion("recipient_address >", value, "recipientAddress");
            return (Criteria) this;
        }

        public Criteria andRecipientAddressGreaterThanOrEqualTo(String value) {
            addCriterion("recipient_address >=", value, "recipientAddress");
            return (Criteria) this;
        }

        public Criteria andRecipientAddressLessThan(String value) {
            addCriterion("recipient_address <", value, "recipientAddress");
            return (Criteria) this;
        }

        public Criteria andRecipientAddressLessThanOrEqualTo(String value) {
            addCriterion("recipient_address <=", value, "recipientAddress");
            return (Criteria) this;
        }

        public Criteria andRecipientAddressLike(String value) {
            addCriterion("recipient_address like", value, "recipientAddress");
            return (Criteria) this;
        }

        public Criteria andRecipientAddressNotLike(String value) {
            addCriterion("recipient_address not like", value, "recipientAddress");
            return (Criteria) this;
        }

        public Criteria andRecipientAddressIn(List<String> values) {
            addCriterion("recipient_address in", values, "recipientAddress");
            return (Criteria) this;
        }

        public Criteria andRecipientAddressNotIn(List<String> values) {
            addCriterion("recipient_address not in", values, "recipientAddress");
            return (Criteria) this;
        }

        public Criteria andRecipientAddressBetween(String value1, String value2) {
            addCriterion("recipient_address between", value1, value2, "recipientAddress");
            return (Criteria) this;
        }

        public Criteria andRecipientAddressNotBetween(String value1, String value2) {
            addCriterion("recipient_address not between", value1, value2, "recipientAddress");
            return (Criteria) this;
        }

        public Criteria andCompanyStatusIsNull() {
            addCriterion("company_status is null");
            return (Criteria) this;
        }

        public Criteria andCompanyStatusIsNotNull() {
            addCriterion("company_status is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyStatusEqualTo(Boolean value) {
            addCriterion("company_status =", value, "companyStatus");
            return (Criteria) this;
        }

        public Criteria andCompanyStatusNotEqualTo(Boolean value) {
            addCriterion("company_status <>", value, "companyStatus");
            return (Criteria) this;
        }

        public Criteria andCompanyStatusGreaterThan(Boolean value) {
            addCriterion("company_status >", value, "companyStatus");
            return (Criteria) this;
        }

        public Criteria andCompanyStatusGreaterThanOrEqualTo(Boolean value) {
            addCriterion("company_status >=", value, "companyStatus");
            return (Criteria) this;
        }

        public Criteria andCompanyStatusLessThan(Boolean value) {
            addCriterion("company_status <", value, "companyStatus");
            return (Criteria) this;
        }

        public Criteria andCompanyStatusLessThanOrEqualTo(Boolean value) {
            addCriterion("company_status <=", value, "companyStatus");
            return (Criteria) this;
        }

        public Criteria andCompanyStatusIn(List<Boolean> values) {
            addCriterion("company_status in", values, "companyStatus");
            return (Criteria) this;
        }

        public Criteria andCompanyStatusNotIn(List<Boolean> values) {
            addCriterion("company_status not in", values, "companyStatus");
            return (Criteria) this;
        }

        public Criteria andCompanyStatusBetween(Boolean value1, Boolean value2) {
            addCriterion("company_status between", value1, value2, "companyStatus");
            return (Criteria) this;
        }

        public Criteria andCompanyStatusNotBetween(Boolean value1, Boolean value2) {
            addCriterion("company_status not between", value1, value2, "companyStatus");
            return (Criteria) this;
        }

        public Criteria andCreatorIdIsNull() {
            addCriterion("creator_id is null");
            return (Criteria) this;
        }

        public Criteria andCreatorIdIsNotNull() {
            addCriterion("creator_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorIdEqualTo(Integer value) {
            addCriterion("creator_id =", value, "creatorId");
            return (Criteria) this;
        }

        public Criteria andCreatorIdNotEqualTo(Integer value) {
            addCriterion("creator_id <>", value, "creatorId");
            return (Criteria) this;
        }

        public Criteria andCreatorIdGreaterThan(Integer value) {
            addCriterion("creator_id >", value, "creatorId");
            return (Criteria) this;
        }

        public Criteria andCreatorIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("creator_id >=", value, "creatorId");
            return (Criteria) this;
        }

        public Criteria andCreatorIdLessThan(Integer value) {
            addCriterion("creator_id <", value, "creatorId");
            return (Criteria) this;
        }

        public Criteria andCreatorIdLessThanOrEqualTo(Integer value) {
            addCriterion("creator_id <=", value, "creatorId");
            return (Criteria) this;
        }

        public Criteria andCreatorIdIn(List<Integer> values) {
            addCriterion("creator_id in", values, "creatorId");
            return (Criteria) this;
        }

        public Criteria andCreatorIdNotIn(List<Integer> values) {
            addCriterion("creator_id not in", values, "creatorId");
            return (Criteria) this;
        }

        public Criteria andCreatorIdBetween(Integer value1, Integer value2) {
            addCriterion("creator_id between", value1, value2, "creatorId");
            return (Criteria) this;
        }

        public Criteria andCreatorIdNotBetween(Integer value1, Integer value2) {
            addCriterion("creator_id not between", value1, value2, "creatorId");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("create_date is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("create_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("create_date =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("create_date <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("create_date >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("create_date >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("create_date <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("create_date <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("create_date in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("create_date not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("create_date between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("create_date not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andUpdateIdIsNull() {
            addCriterion("update_id is null");
            return (Criteria) this;
        }

        public Criteria andUpdateIdIsNotNull() {
            addCriterion("update_id is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateIdEqualTo(Integer value) {
            addCriterion("update_id =", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdNotEqualTo(Integer value) {
            addCriterion("update_id <>", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdGreaterThan(Integer value) {
            addCriterion("update_id >", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("update_id >=", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdLessThan(Integer value) {
            addCriterion("update_id <", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdLessThanOrEqualTo(Integer value) {
            addCriterion("update_id <=", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdIn(List<Integer> values) {
            addCriterion("update_id in", values, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdNotIn(List<Integer> values) {
            addCriterion("update_id not in", values, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdBetween(Integer value1, Integer value2) {
            addCriterion("update_id between", value1, value2, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdNotBetween(Integer value1, Integer value2) {
            addCriterion("update_id not between", value1, value2, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("update_date is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("update_date is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(Date value) {
            addCriterion("update_date =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(Date value) {
            addCriterion("update_date <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(Date value) {
            addCriterion("update_date >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("update_date >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(Date value) {
            addCriterion("update_date <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("update_date <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<Date> values) {
            addCriterion("update_date in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<Date> values) {
            addCriterion("update_date not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(Date value1, Date value2) {
            addCriterion("update_date between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("update_date not between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andCompanyTypeIsNull() {
            addCriterion("company_type is null");
            return (Criteria) this;
        }

        public Criteria andCompanyTypeIsNotNull() {
            addCriterion("company_type is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyTypeEqualTo(Boolean value) {
            addCriterion("company_type =", value, "companyType");
            return (Criteria) this;
        }

        public Criteria andCompanyTypeNotEqualTo(Boolean value) {
            addCriterion("company_type <>", value, "companyType");
            return (Criteria) this;
        }

        public Criteria andCompanyTypeGreaterThan(Boolean value) {
            addCriterion("company_type >", value, "companyType");
            return (Criteria) this;
        }

        public Criteria andCompanyTypeGreaterThanOrEqualTo(Boolean value) {
            addCriterion("company_type >=", value, "companyType");
            return (Criteria) this;
        }

        public Criteria andCompanyTypeLessThan(Boolean value) {
            addCriterion("company_type <", value, "companyType");
            return (Criteria) this;
        }

        public Criteria andCompanyTypeLessThanOrEqualTo(Boolean value) {
            addCriterion("company_type <=", value, "companyType");
            return (Criteria) this;
        }

        public Criteria andCompanyTypeIn(List<Boolean> values) {
            addCriterion("company_type in", values, "companyType");
            return (Criteria) this;
        }

        public Criteria andCompanyTypeNotIn(List<Boolean> values) {
            addCriterion("company_type not in", values, "companyType");
            return (Criteria) this;
        }

        public Criteria andCompanyTypeBetween(Boolean value1, Boolean value2) {
            addCriterion("company_type between", value1, value2, "companyType");
            return (Criteria) this;
        }

        public Criteria andCompanyTypeNotBetween(Boolean value1, Boolean value2) {
            addCriterion("company_type not between", value1, value2, "companyType");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table neo_company
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table neo_company
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}