package com.example.neo.mybatis.model;

import java.io.Serializable;
import java.util.Date;

public class neoInvoice implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neo_invoice.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neo_invoice.order_number
     *
     * @mbg.generated
     */
    private String orderNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neo_invoice.invoice_content
     *
     * @mbg.generated
     */
    private String invoiceContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neo_invoice.invoice_type
     *
     * @mbg.generated
     */
    private Boolean invoiceType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neo_invoice.invoice_amount
     *
     * @mbg.generated
     */
    private Double invoiceAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neo_invoice.invoice_company
     *
     * @mbg.generated
     */
    private String invoiceCompany;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neo_invoice.receive_name
     *
     * @mbg.generated
     */
    private String receiveName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neo_invoice.receive_tel
     *
     * @mbg.generated
     */
    private String receiveTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neo_invoice.receive_address
     *
     * @mbg.generated
     */
    private String receiveAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neo_invoice.status
     *
     * @mbg.generated
     */
    private Boolean status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neo_invoice.creator_id
     *
     * @mbg.generated
     */
    private Integer creatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neo_invoice.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neo_invoice.update_id
     *
     * @mbg.generated
     */
    private Integer updateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neo_invoice.update_date
     *
     * @mbg.generated
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table neo_invoice
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neo_invoice.id
     *
     * @return the value of neo_invoice.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neo_invoice.id
     *
     * @param id the value for neo_invoice.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neo_invoice.order_number
     *
     * @return the value of neo_invoice.order_number
     *
     * @mbg.generated
     */
    public String getOrderNumber() {
        return orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neo_invoice.order_number
     *
     * @param orderNumber the value for neo_invoice.order_number
     *
     * @mbg.generated
     */
    public void setOrderNumber(String orderNumber) {
        this.orderNumber = orderNumber == null ? null : orderNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neo_invoice.invoice_content
     *
     * @return the value of neo_invoice.invoice_content
     *
     * @mbg.generated
     */
    public String getInvoiceContent() {
        return invoiceContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neo_invoice.invoice_content
     *
     * @param invoiceContent the value for neo_invoice.invoice_content
     *
     * @mbg.generated
     */
    public void setInvoiceContent(String invoiceContent) {
        this.invoiceContent = invoiceContent == null ? null : invoiceContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neo_invoice.invoice_type
     *
     * @return the value of neo_invoice.invoice_type
     *
     * @mbg.generated
     */
    public Boolean getInvoiceType() {
        return invoiceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neo_invoice.invoice_type
     *
     * @param invoiceType the value for neo_invoice.invoice_type
     *
     * @mbg.generated
     */
    public void setInvoiceType(Boolean invoiceType) {
        this.invoiceType = invoiceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neo_invoice.invoice_amount
     *
     * @return the value of neo_invoice.invoice_amount
     *
     * @mbg.generated
     */
    public Double getInvoiceAmount() {
        return invoiceAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neo_invoice.invoice_amount
     *
     * @param invoiceAmount the value for neo_invoice.invoice_amount
     *
     * @mbg.generated
     */
    public void setInvoiceAmount(Double invoiceAmount) {
        this.invoiceAmount = invoiceAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neo_invoice.invoice_company
     *
     * @return the value of neo_invoice.invoice_company
     *
     * @mbg.generated
     */
    public String getInvoiceCompany() {
        return invoiceCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neo_invoice.invoice_company
     *
     * @param invoiceCompany the value for neo_invoice.invoice_company
     *
     * @mbg.generated
     */
    public void setInvoiceCompany(String invoiceCompany) {
        this.invoiceCompany = invoiceCompany == null ? null : invoiceCompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neo_invoice.receive_name
     *
     * @return the value of neo_invoice.receive_name
     *
     * @mbg.generated
     */
    public String getReceiveName() {
        return receiveName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neo_invoice.receive_name
     *
     * @param receiveName the value for neo_invoice.receive_name
     *
     * @mbg.generated
     */
    public void setReceiveName(String receiveName) {
        this.receiveName = receiveName == null ? null : receiveName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neo_invoice.receive_tel
     *
     * @return the value of neo_invoice.receive_tel
     *
     * @mbg.generated
     */
    public String getReceiveTel() {
        return receiveTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neo_invoice.receive_tel
     *
     * @param receiveTel the value for neo_invoice.receive_tel
     *
     * @mbg.generated
     */
    public void setReceiveTel(String receiveTel) {
        this.receiveTel = receiveTel == null ? null : receiveTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neo_invoice.receive_address
     *
     * @return the value of neo_invoice.receive_address
     *
     * @mbg.generated
     */
    public String getReceiveAddress() {
        return receiveAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neo_invoice.receive_address
     *
     * @param receiveAddress the value for neo_invoice.receive_address
     *
     * @mbg.generated
     */
    public void setReceiveAddress(String receiveAddress) {
        this.receiveAddress = receiveAddress == null ? null : receiveAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neo_invoice.status
     *
     * @return the value of neo_invoice.status
     *
     * @mbg.generated
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neo_invoice.status
     *
     * @param status the value for neo_invoice.status
     *
     * @mbg.generated
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neo_invoice.creator_id
     *
     * @return the value of neo_invoice.creator_id
     *
     * @mbg.generated
     */
    public Integer getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neo_invoice.creator_id
     *
     * @param creatorId the value for neo_invoice.creator_id
     *
     * @mbg.generated
     */
    public void setCreatorId(Integer creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neo_invoice.create_date
     *
     * @return the value of neo_invoice.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neo_invoice.create_date
     *
     * @param createDate the value for neo_invoice.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neo_invoice.update_id
     *
     * @return the value of neo_invoice.update_id
     *
     * @mbg.generated
     */
    public Integer getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neo_invoice.update_id
     *
     * @param updateId the value for neo_invoice.update_id
     *
     * @mbg.generated
     */
    public void setUpdateId(Integer updateId) {
        this.updateId = updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neo_invoice.update_date
     *
     * @return the value of neo_invoice.update_date
     *
     * @mbg.generated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neo_invoice.update_date
     *
     * @param updateDate the value for neo_invoice.update_date
     *
     * @mbg.generated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_invoice
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        neoInvoice other = (neoInvoice) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getOrderNumber() == null ? other.getOrderNumber() == null : this.getOrderNumber().equals(other.getOrderNumber()))
            && (this.getInvoiceContent() == null ? other.getInvoiceContent() == null : this.getInvoiceContent().equals(other.getInvoiceContent()))
            && (this.getInvoiceType() == null ? other.getInvoiceType() == null : this.getInvoiceType().equals(other.getInvoiceType()))
            && (this.getInvoiceAmount() == null ? other.getInvoiceAmount() == null : this.getInvoiceAmount().equals(other.getInvoiceAmount()))
            && (this.getInvoiceCompany() == null ? other.getInvoiceCompany() == null : this.getInvoiceCompany().equals(other.getInvoiceCompany()))
            && (this.getReceiveName() == null ? other.getReceiveName() == null : this.getReceiveName().equals(other.getReceiveName()))
            && (this.getReceiveTel() == null ? other.getReceiveTel() == null : this.getReceiveTel().equals(other.getReceiveTel()))
            && (this.getReceiveAddress() == null ? other.getReceiveAddress() == null : this.getReceiveAddress().equals(other.getReceiveAddress()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getCreatorId() == null ? other.getCreatorId() == null : this.getCreatorId().equals(other.getCreatorId()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getUpdateId() == null ? other.getUpdateId() == null : this.getUpdateId().equals(other.getUpdateId()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_invoice
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getOrderNumber() == null) ? 0 : getOrderNumber().hashCode());
        result = prime * result + ((getInvoiceContent() == null) ? 0 : getInvoiceContent().hashCode());
        result = prime * result + ((getInvoiceType() == null) ? 0 : getInvoiceType().hashCode());
        result = prime * result + ((getInvoiceAmount() == null) ? 0 : getInvoiceAmount().hashCode());
        result = prime * result + ((getInvoiceCompany() == null) ? 0 : getInvoiceCompany().hashCode());
        result = prime * result + ((getReceiveName() == null) ? 0 : getReceiveName().hashCode());
        result = prime * result + ((getReceiveTel() == null) ? 0 : getReceiveTel().hashCode());
        result = prime * result + ((getReceiveAddress() == null) ? 0 : getReceiveAddress().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getCreatorId() == null) ? 0 : getCreatorId().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getUpdateId() == null) ? 0 : getUpdateId().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_invoice
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", orderNumber=").append(orderNumber);
        sb.append(", invoiceContent=").append(invoiceContent);
        sb.append(", invoiceType=").append(invoiceType);
        sb.append(", invoiceAmount=").append(invoiceAmount);
        sb.append(", invoiceCompany=").append(invoiceCompany);
        sb.append(", receiveName=").append(receiveName);
        sb.append(", receiveTel=").append(receiveTel);
        sb.append(", receiveAddress=").append(receiveAddress);
        sb.append(", status=").append(status);
        sb.append(", creatorId=").append(creatorId);
        sb.append(", createDate=").append(createDate);
        sb.append(", updateId=").append(updateId);
        sb.append(", updateDate=").append(updateDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}