package com.example.neo.mybatis.model;

import java.io.Serializable;
import java.util.Date;

public class neoRechargeRecord implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neo_recharge_record.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neo_recharge_record.order_number
     *
     * @mbg.generated
     */
    private String orderNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neo_recharge_record.company_id
     *
     * @mbg.generated
     */
    private Integer companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neo_recharge_record.payment_amount
     *
     * @mbg.generated
     */
    private Double paymentAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neo_recharge_record.account_amount
     *
     * @mbg.generated
     */
    private Double accountAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neo_recharge_record.payment_voucher
     *
     * @mbg.generated
     */
    private String paymentVoucher;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neo_recharge_record.invoicing_status
     *
     * @mbg.generated
     */
    private Boolean invoicingStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neo_recharge_record.approval_status
     *
     * @mbg.generated
     */
    private Boolean approvalStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neo_recharge_record.creator_id
     *
     * @mbg.generated
     */
    private Integer creatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neo_recharge_record.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neo_recharge_record.update_id
     *
     * @mbg.generated
     */
    private Integer updateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neo_recharge_record.update_date
     *
     * @mbg.generated
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table neo_recharge_record
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neo_recharge_record.id
     *
     * @return the value of neo_recharge_record.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neo_recharge_record.id
     *
     * @param id the value for neo_recharge_record.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neo_recharge_record.order_number
     *
     * @return the value of neo_recharge_record.order_number
     *
     * @mbg.generated
     */
    public String getOrderNumber() {
        return orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neo_recharge_record.order_number
     *
     * @param orderNumber the value for neo_recharge_record.order_number
     *
     * @mbg.generated
     */
    public void setOrderNumber(String orderNumber) {
        this.orderNumber = orderNumber == null ? null : orderNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neo_recharge_record.company_id
     *
     * @return the value of neo_recharge_record.company_id
     *
     * @mbg.generated
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neo_recharge_record.company_id
     *
     * @param companyId the value for neo_recharge_record.company_id
     *
     * @mbg.generated
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neo_recharge_record.payment_amount
     *
     * @return the value of neo_recharge_record.payment_amount
     *
     * @mbg.generated
     */
    public Double getPaymentAmount() {
        return paymentAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neo_recharge_record.payment_amount
     *
     * @param paymentAmount the value for neo_recharge_record.payment_amount
     *
     * @mbg.generated
     */
    public void setPaymentAmount(Double paymentAmount) {
        this.paymentAmount = paymentAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neo_recharge_record.account_amount
     *
     * @return the value of neo_recharge_record.account_amount
     *
     * @mbg.generated
     */
    public Double getAccountAmount() {
        return accountAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neo_recharge_record.account_amount
     *
     * @param accountAmount the value for neo_recharge_record.account_amount
     *
     * @mbg.generated
     */
    public void setAccountAmount(Double accountAmount) {
        this.accountAmount = accountAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neo_recharge_record.payment_voucher
     *
     * @return the value of neo_recharge_record.payment_voucher
     *
     * @mbg.generated
     */
    public String getPaymentVoucher() {
        return paymentVoucher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neo_recharge_record.payment_voucher
     *
     * @param paymentVoucher the value for neo_recharge_record.payment_voucher
     *
     * @mbg.generated
     */
    public void setPaymentVoucher(String paymentVoucher) {
        this.paymentVoucher = paymentVoucher == null ? null : paymentVoucher.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neo_recharge_record.invoicing_status
     *
     * @return the value of neo_recharge_record.invoicing_status
     *
     * @mbg.generated
     */
    public Boolean getInvoicingStatus() {
        return invoicingStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neo_recharge_record.invoicing_status
     *
     * @param invoicingStatus the value for neo_recharge_record.invoicing_status
     *
     * @mbg.generated
     */
    public void setInvoicingStatus(Boolean invoicingStatus) {
        this.invoicingStatus = invoicingStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neo_recharge_record.approval_status
     *
     * @return the value of neo_recharge_record.approval_status
     *
     * @mbg.generated
     */
    public Boolean getApprovalStatus() {
        return approvalStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neo_recharge_record.approval_status
     *
     * @param approvalStatus the value for neo_recharge_record.approval_status
     *
     * @mbg.generated
     */
    public void setApprovalStatus(Boolean approvalStatus) {
        this.approvalStatus = approvalStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neo_recharge_record.creator_id
     *
     * @return the value of neo_recharge_record.creator_id
     *
     * @mbg.generated
     */
    public Integer getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neo_recharge_record.creator_id
     *
     * @param creatorId the value for neo_recharge_record.creator_id
     *
     * @mbg.generated
     */
    public void setCreatorId(Integer creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neo_recharge_record.create_date
     *
     * @return the value of neo_recharge_record.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neo_recharge_record.create_date
     *
     * @param createDate the value for neo_recharge_record.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neo_recharge_record.update_id
     *
     * @return the value of neo_recharge_record.update_id
     *
     * @mbg.generated
     */
    public Integer getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neo_recharge_record.update_id
     *
     * @param updateId the value for neo_recharge_record.update_id
     *
     * @mbg.generated
     */
    public void setUpdateId(Integer updateId) {
        this.updateId = updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neo_recharge_record.update_date
     *
     * @return the value of neo_recharge_record.update_date
     *
     * @mbg.generated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neo_recharge_record.update_date
     *
     * @param updateDate the value for neo_recharge_record.update_date
     *
     * @mbg.generated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_recharge_record
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        neoRechargeRecord other = (neoRechargeRecord) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getOrderNumber() == null ? other.getOrderNumber() == null : this.getOrderNumber().equals(other.getOrderNumber()))
            && (this.getCompanyId() == null ? other.getCompanyId() == null : this.getCompanyId().equals(other.getCompanyId()))
            && (this.getPaymentAmount() == null ? other.getPaymentAmount() == null : this.getPaymentAmount().equals(other.getPaymentAmount()))
            && (this.getAccountAmount() == null ? other.getAccountAmount() == null : this.getAccountAmount().equals(other.getAccountAmount()))
            && (this.getPaymentVoucher() == null ? other.getPaymentVoucher() == null : this.getPaymentVoucher().equals(other.getPaymentVoucher()))
            && (this.getInvoicingStatus() == null ? other.getInvoicingStatus() == null : this.getInvoicingStatus().equals(other.getInvoicingStatus()))
            && (this.getApprovalStatus() == null ? other.getApprovalStatus() == null : this.getApprovalStatus().equals(other.getApprovalStatus()))
            && (this.getCreatorId() == null ? other.getCreatorId() == null : this.getCreatorId().equals(other.getCreatorId()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getUpdateId() == null ? other.getUpdateId() == null : this.getUpdateId().equals(other.getUpdateId()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_recharge_record
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getOrderNumber() == null) ? 0 : getOrderNumber().hashCode());
        result = prime * result + ((getCompanyId() == null) ? 0 : getCompanyId().hashCode());
        result = prime * result + ((getPaymentAmount() == null) ? 0 : getPaymentAmount().hashCode());
        result = prime * result + ((getAccountAmount() == null) ? 0 : getAccountAmount().hashCode());
        result = prime * result + ((getPaymentVoucher() == null) ? 0 : getPaymentVoucher().hashCode());
        result = prime * result + ((getInvoicingStatus() == null) ? 0 : getInvoicingStatus().hashCode());
        result = prime * result + ((getApprovalStatus() == null) ? 0 : getApprovalStatus().hashCode());
        result = prime * result + ((getCreatorId() == null) ? 0 : getCreatorId().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getUpdateId() == null) ? 0 : getUpdateId().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_recharge_record
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", orderNumber=").append(orderNumber);
        sb.append(", companyId=").append(companyId);
        sb.append(", paymentAmount=").append(paymentAmount);
        sb.append(", accountAmount=").append(accountAmount);
        sb.append(", paymentVoucher=").append(paymentVoucher);
        sb.append(", invoicingStatus=").append(invoicingStatus);
        sb.append(", approvalStatus=").append(approvalStatus);
        sb.append(", creatorId=").append(creatorId);
        sb.append(", createDate=").append(createDate);
        sb.append(", updateId=").append(updateId);
        sb.append(", updateDate=").append(updateDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}