package com.example.neo.mybatis.model.mapper;

import com.example.neo.mybatis.model.neoCompany;
import com.example.neo.mybatis.model.neoCompanyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface neoCompanyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_company
     *
     * @mbg.generated
     */
    long countByExample(neoCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_company
     *
     * @mbg.generated
     */
    int deleteByExample(neoCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_company
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_company
     *
     * @mbg.generated
     */
    int insert(neoCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_company
     *
     * @mbg.generated
     */
    int insertSelective(neoCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_company
     *
     * @mbg.generated
     */
    List<neoCompany> selectByExample(neoCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_company
     *
     * @mbg.generated
     */
    neoCompany selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_company
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") neoCompany record, @Param("example") neoCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_company
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") neoCompany record, @Param("example") neoCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_company
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(neoCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_company
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(neoCompany record);
}