package com.example.neo.mybatis.model.mapper;

import com.example.neo.mybatis.model.neoCompanyRelation;
import com.example.neo.mybatis.model.neoCompanyRelationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface neoCompanyRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_company_relation
     *
     * @mbg.generated
     */
    long countByExample(neoCompanyRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_company_relation
     *
     * @mbg.generated
     */
    int deleteByExample(neoCompanyRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_company_relation
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_company_relation
     *
     * @mbg.generated
     */
    int insert(neoCompanyRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_company_relation
     *
     * @mbg.generated
     */
    int insertSelective(neoCompanyRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_company_relation
     *
     * @mbg.generated
     */
    List<neoCompanyRelation> selectByExample(neoCompanyRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_company_relation
     *
     * @mbg.generated
     */
    neoCompanyRelation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_company_relation
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") neoCompanyRelation record, @Param("example") neoCompanyRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_company_relation
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") neoCompanyRelation record, @Param("example") neoCompanyRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_company_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(neoCompanyRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_company_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(neoCompanyRelation record);
}