package com.example.neo.mybatis.model.mapper;

import com.example.neo.mybatis.model.NeoCompanyRelation;
import com.example.neo.mybatis.model.NeoCompanyRelationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NeoCompanyRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_company_relation
     *
     * @mbg.generated
     */
    long countByExample(NeoCompanyRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_company_relation
     *
     * @mbg.generated
     */
    int deleteByExample(NeoCompanyRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_company_relation
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_company_relation
     *
     * @mbg.generated
     */
    int insert(NeoCompanyRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_company_relation
     *
     * @mbg.generated
     */
    int insertSelective(NeoCompanyRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_company_relation
     *
     * @mbg.generated
     */
    List<NeoCompanyRelation> selectByExample(NeoCompanyRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_company_relation
     *
     * @mbg.generated
     */
    NeoCompanyRelation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_company_relation
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") NeoCompanyRelation record, @Param("example") NeoCompanyRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_company_relation
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") NeoCompanyRelation record, @Param("example") NeoCompanyRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_company_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(NeoCompanyRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_company_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(NeoCompanyRelation record);
}