package com.example.neo.mybatis.model.mapper;

import com.example.neo.mybatis.model.neoCompanyTax;
import com.example.neo.mybatis.model.neoCompanyTaxExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface neoCompanyTaxMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_company_tax
     *
     * @mbg.generated
     */
    long countByExample(neoCompanyTaxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_company_tax
     *
     * @mbg.generated
     */
    int deleteByExample(neoCompanyTaxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_company_tax
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_company_tax
     *
     * @mbg.generated
     */
    int insert(neoCompanyTax record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_company_tax
     *
     * @mbg.generated
     */
    int insertSelective(neoCompanyTax record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_company_tax
     *
     * @mbg.generated
     */
    List<neoCompanyTax> selectByExample(neoCompanyTaxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_company_tax
     *
     * @mbg.generated
     */
    neoCompanyTax selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_company_tax
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") neoCompanyTax record, @Param("example") neoCompanyTaxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_company_tax
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") neoCompanyTax record, @Param("example") neoCompanyTaxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_company_tax
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(neoCompanyTax record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_company_tax
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(neoCompanyTax record);
}