package com.example.neo.mybatis.model.mapper;

import com.example.neo.mybatis.model.neoEmployee;
import com.example.neo.mybatis.model.neoEmployeeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface neoEmployeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_employee
     *
     * @mbg.generated
     */
    long countByExample(neoEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_employee
     *
     * @mbg.generated
     */
    int deleteByExample(neoEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_employee
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_employee
     *
     * @mbg.generated
     */
    int insert(neoEmployee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_employee
     *
     * @mbg.generated
     */
    int insertSelective(neoEmployee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_employee
     *
     * @mbg.generated
     */
    List<neoEmployee> selectByExample(neoEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_employee
     *
     * @mbg.generated
     */
    neoEmployee selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_employee
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") neoEmployee record, @Param("example") neoEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_employee
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") neoEmployee record, @Param("example") neoEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_employee
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(neoEmployee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_employee
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(neoEmployee record);
}