package com.example.neo.mybatis.model.mapper;

import com.example.neo.mybatis.model.neoFinance;
import com.example.neo.mybatis.model.neoFinanceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface neoFinanceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_finance
     *
     * @mbg.generated
     */
    long countByExample(neoFinanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_finance
     *
     * @mbg.generated
     */
    int deleteByExample(neoFinanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_finance
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_finance
     *
     * @mbg.generated
     */
    int insert(neoFinance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_finance
     *
     * @mbg.generated
     */
    int insertSelective(neoFinance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_finance
     *
     * @mbg.generated
     */
    List<neoFinance> selectByExample(neoFinanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_finance
     *
     * @mbg.generated
     */
    neoFinance selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_finance
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") neoFinance record, @Param("example") neoFinanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_finance
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") neoFinance record, @Param("example") neoFinanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_finance
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(neoFinance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_finance
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(neoFinance record);
}