package com.example.neo.mybatis.model.mapper;

import com.example.neo.mybatis.model.neoIssue;
import com.example.neo.mybatis.model.neoIssueExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface neoIssueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_issue
     *
     * @mbg.generated
     */
    long countByExample(neoIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_issue
     *
     * @mbg.generated
     */
    int deleteByExample(neoIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_issue
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_issue
     *
     * @mbg.generated
     */
    int insert(neoIssue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_issue
     *
     * @mbg.generated
     */
    int insertSelective(neoIssue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_issue
     *
     * @mbg.generated
     */
    List<neoIssue> selectByExample(neoIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_issue
     *
     * @mbg.generated
     */
    neoIssue selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_issue
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") neoIssue record, @Param("example") neoIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_issue
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") neoIssue record, @Param("example") neoIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_issue
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(neoIssue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_issue
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(neoIssue record);
}