package com.example.neo.mybatis.model.mapper;

import com.example.neo.mybatis.model.NeoIssueDetail;
import com.example.neo.mybatis.model.NeoIssueDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NeoIssueDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_issue_detail
     *
     * @mbg.generated
     */
    long countByExample(NeoIssueDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_issue_detail
     *
     * @mbg.generated
     */
    int deleteByExample(NeoIssueDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_issue_detail
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_issue_detail
     *
     * @mbg.generated
     */
    int insert(NeoIssueDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_issue_detail
     *
     * @mbg.generated
     */
    int insertSelective(NeoIssueDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_issue_detail
     *
     * @mbg.generated
     */
    List<NeoIssueDetail> selectByExample(NeoIssueDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_issue_detail
     *
     * @mbg.generated
     */
    NeoIssueDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_issue_detail
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") NeoIssueDetail record, @Param("example") NeoIssueDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_issue_detail
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") NeoIssueDetail record, @Param("example") NeoIssueDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_issue_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(NeoIssueDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_issue_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(NeoIssueDetail record);
}