package com.example.neo.mybatis.model.mapper;

import com.example.neo.mybatis.model.neoRole;
import com.example.neo.mybatis.model.neoRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface neoRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_role
     *
     * @mbg.generated
     */
    long countByExample(neoRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_role
     *
     * @mbg.generated
     */
    int deleteByExample(neoRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_role
     *
     * @mbg.generated
     */
    int insert(neoRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_role
     *
     * @mbg.generated
     */
    int insertSelective(neoRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_role
     *
     * @mbg.generated
     */
    List<neoRole> selectByExample(neoRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_role
     *
     * @mbg.generated
     */
    neoRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_role
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") neoRole record, @Param("example") neoRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_role
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") neoRole record, @Param("example") neoRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(neoRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(neoRole record);
}