package com.example.neo.mybatis.model.mapper;

import com.example.neo.mybatis.model.neoRechargeRecord;
import com.example.neo.mybatis.model.neoRechargeRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface neoRechargeRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_recharge_record
     *
     * @mbg.generated
     */
    long countByExample(neoRechargeRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_recharge_record
     *
     * @mbg.generated
     */
    int deleteByExample(neoRechargeRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_recharge_record
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_recharge_record
     *
     * @mbg.generated
     */
    int insert(neoRechargeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_recharge_record
     *
     * @mbg.generated
     */
    int insertSelective(neoRechargeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_recharge_record
     *
     * @mbg.generated
     */
    List<neoRechargeRecord> selectByExample(neoRechargeRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_recharge_record
     *
     * @mbg.generated
     */
    neoRechargeRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_recharge_record
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") neoRechargeRecord record, @Param("example") neoRechargeRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_recharge_record
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") neoRechargeRecord record, @Param("example") neoRechargeRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_recharge_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(neoRechargeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_recharge_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(neoRechargeRecord record);
}