package com.example.neo.mybatis.model.mapper;

import com.example.neo.mybatis.model.neoRoleFunction;
import com.example.neo.mybatis.model.neoRoleFunctionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface neoRoleFunctionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_role_function
     *
     * @mbg.generated
     */
    long countByExample(neoRoleFunctionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_role_function
     *
     * @mbg.generated
     */
    int deleteByExample(neoRoleFunctionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_role_function
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_role_function
     *
     * @mbg.generated
     */
    int insert(neoRoleFunction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_role_function
     *
     * @mbg.generated
     */
    int insertSelective(neoRoleFunction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_role_function
     *
     * @mbg.generated
     */
    List<neoRoleFunction> selectByExample(neoRoleFunctionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_role_function
     *
     * @mbg.generated
     */
    neoRoleFunction selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_role_function
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") neoRoleFunction record, @Param("example") neoRoleFunctionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_role_function
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") neoRoleFunction record, @Param("example") neoRoleFunctionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_role_function
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(neoRoleFunction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_role_function
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(neoRoleFunction record);
}