package com.example.neo.mybatis.model.mapper;

import com.example.neo.mybatis.model.NeoRoleFunction;
import com.example.neo.mybatis.model.NeoRoleFunctionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NeoRoleFunctionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_role_function
     *
     * @mbg.generated
     */
    long countByExample(NeoRoleFunctionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_role_function
     *
     * @mbg.generated
     */
    int deleteByExample(NeoRoleFunctionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_role_function
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_role_function
     *
     * @mbg.generated
     */
    int insert(NeoRoleFunction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_role_function
     *
     * @mbg.generated
     */
    int insertSelective(NeoRoleFunction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_role_function
     *
     * @mbg.generated
     */
    List<NeoRoleFunction> selectByExample(NeoRoleFunctionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_role_function
     *
     * @mbg.generated
     */
    NeoRoleFunction selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_role_function
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") NeoRoleFunction record, @Param("example") NeoRoleFunctionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_role_function
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") NeoRoleFunction record, @Param("example") NeoRoleFunctionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_role_function
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(NeoRoleFunction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_role_function
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(NeoRoleFunction record);
}