package com.example.neo.mybatis.model.mapper;

import com.example.neo.mybatis.model.neoUser;
import com.example.neo.mybatis.model.neoUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface neoUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_user
     *
     * @mbg.generated
     */
    long countByExample(neoUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_user
     *
     * @mbg.generated
     */
    int deleteByExample(neoUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_user
     *
     * @mbg.generated
     */
    int insert(neoUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_user
     *
     * @mbg.generated
     */
    int insertSelective(neoUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_user
     *
     * @mbg.generated
     */
    List<neoUser> selectByExample(neoUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_user
     *
     * @mbg.generated
     */
    neoUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") neoUser record, @Param("example") neoUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") neoUser record, @Param("example") neoUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(neoUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(neoUser record);
}