package com.example.neo.mybatis.model.mapper;

import com.example.neo.mybatis.model.neoWithdraw;
import com.example.neo.mybatis.model.neoWithdrawExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface neoWithdrawMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_withdraw
     *
     * @mbg.generated
     */
    long countByExample(neoWithdrawExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_withdraw
     *
     * @mbg.generated
     */
    int deleteByExample(neoWithdrawExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_withdraw
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_withdraw
     *
     * @mbg.generated
     */
    int insert(neoWithdraw record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_withdraw
     *
     * @mbg.generated
     */
    int insertSelective(neoWithdraw record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_withdraw
     *
     * @mbg.generated
     */
    List<neoWithdraw> selectByExample(neoWithdrawExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_withdraw
     *
     * @mbg.generated
     */
    neoWithdraw selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_withdraw
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") neoWithdraw record, @Param("example") neoWithdrawExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_withdraw
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") neoWithdraw record, @Param("example") neoWithdrawExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_withdraw
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(neoWithdraw record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neo_withdraw
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(neoWithdraw record);
}