# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: NEO CI

on:
  push:
    branches:
      - master

jobs:
    
  fe-job:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: use nodejs
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: build
      run: |
        cd $GITHUB_WORKSPACE/neo-fe
        npm ci
        npm run build
    
    - name: deploy to server
      uses: easingthemes/ssh-deploy@v2.1.5
      with: 
        SOURCE: "neo-fe/build/*"
        ARGS: "-rltgoDzvO"
        TARGET: ${{ secrets.REMOTE_FE }}
        REMOTE_HOST: ${{ secrets.HOST }}
        REMOTE_PORT: ${{ secrets.PORT }}
        REMOTE_USER: ${{ secrets.USER }}
        SSH_PRIVATE_KEY: ${{ secrets.ACCESS_TOKEN }}

  java-job:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: build java
      run: |
        cd $GITHUB_WORKSPACE/neo-back
        chmod +x gradlew
        ./gradlew build
    
    - name: deploy to server
      uses: easingthemes/ssh-deploy@v2.1.5
      with: 
        SOURCE: "neo-back/build/*"
        ARGS: "-rltgoDzvO"
        TARGET: ${{ secrets.REMOTE_BACK }}
        REMOTE_HOST: ${{ secrets.HOST }}
        REMOTE_PORT: ${{ secrets.PORT }}
        REMOTE_USER: ${{ secrets.USER }}
        SSH_PRIVATE_KEY: ${{ secrets.ACCESS_TOKEN }}
