# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: NEO CI

on:
  push:
    branches:
      - master

jobs:
    
  fe-job:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: use nodejs
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: build
      run: |
        cd neo-fe
        echo 1111111
        pwd
        echo 222222
    
    - name: deploy to server
      uses: horochx/deploy-via-scp@master
      with: 
        local: ./build/*
        remote: ${{ secrets.REMOTE_FE }}
        host: ${{ secrets.HOST }}
        port: ${{ secrets.PORT }}
        user: ${{ secrets.USER }}
        key: ${{ secrets.ACCESS_TOKEN }}

  # java-job:

  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Set up JDK 1.8
  #     uses: actions/setup-java@v1
  #     with:
  #       java-version: 1.8
  #   - name: build java
  #     run: |
  #       cd neo-back
  #       chmod +x gradlew
  #       ./gradlew build
    
  #   - name: deploy to server
  #     uses: horochx/deploy-via-scp@master
  #     with: 
  #       local: "neo-back"
  #       remote: ${{ secrets.REMOTE_BACK }}
  #       host: ${{ secrets.HOST }}
  #       port: ${{ secrets.PORT }}
  #       user: ${{ secrets.USER }}
  #       key: ${{ secrets.ACCESS_TOKEN }}
