
name: Neo FE CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: use nodejs
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: build
      run: |
        echo pwd
        cd /neo-fe
        npm install
        npm run build
    
    - name: deploy to server
      uses: horochx/deploy-via-scp@master
      with: 
        local: /neo-fe/dist
        remote: ${{ secrets.REMOTE_FE }}
        host: ${{ secrets.HOST }}
        port: ${{ secrets.PORT }}
        user: ${{ secrets.USER }}
        key: ${{ secrets.ACCESS_TOKEN }}
    
